[package]
name = "sdl_mixer"
version = "0.3.5"
authors = [
	"Brian Anderson <banderson@mozilla.com>",
	"Kang Seonghoon <public+rust@mearie.org>"
]

[lib]
name = "sdl_mixer"
path = "lib.rs"

[dependencies.sdl]
path = "../.."
